"""Result tables, written as both CSV and LaTeX for direct inclusion.

Every number the manuscript states about a portfolio, a premium or a
calibrated parameter is produced here, so the text and the code cannot drift
apart.
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

from common import TAB_DIR, save_table, write_values
from scenarios import CONFIDENCES, HEADLINE, climate, solved

from wrcp.calibration import PUBLISHED, calibration_table
from wrcp.regions import EXPOSURE, REGIONS, UNIT_COSTS, build_stores

SI_DIR = os.path.join(TAB_DIR, "tex")
os.makedirs(SI_DIR, exist_ok=True)


def write_tex(df, name, caption, label, float_format="%.3g", index=False):
    """Write a booktabs table body for \\input into the manuscript."""
    path = os.path.join(SI_DIR, name + ".tex")
    body = df.to_latex(
        index=index,
        escape=False,
        float_format=lambda v: format(v, float_format.lstrip("%")),
        column_format="l" + "r" * (df.shape[1] - (0 if index else 1)),
    )
    with open(path, "w") as fh:
        fh.write("% Generated by scripts/make_tables.py -- do not edit by hand.\n")
        fh.write("\\begin{table}[!htbp]\n\\centering\n\\footnotesize\n")
        fh.write("\\caption{{{}}}\n\\label{{{}}}\n".format(caption, label))
        fh.write(body)
        fh.write("\\end{table}\n")
    print("  tex    -> results/tables/tex/{}.tex".format(name))
    return path


# --------------------------------------------------------------------- tables
def table_calibration():
    """Every calibrated fire parameter, with its provenance."""
    df = calibration_table(list(REGIONS.values()))
    save_table(df, "calibration")
    pretty = pd.DataFrame(
        {
            "Region": [REGIONS[r].label for r in df["region"]],
            "Return interval (yr)": df["fire_return_interval_yr"],
            "$\\lambda_0$ (yr$^{-1}$)": df["lambda0_per_yr"],
            "$\\beta_T$ (K$^{-1}$)": df["beta_T_per_K"],
            "$\\beta_D$": df["beta_D"],
            "Intensification": df["intensification_target"],
            "$m_1$": df["severity_m1"],
            "$m_2$": df["severity_m2"],
            "Spread $\\sigma_\\xi$": df["weather_spread"],
        }
    )
    write_tex(
        pretty,
        "calibration",
        "\\textbf{Calibrated fire parameters.} The baseline rate is the "
        "inverse of the published fire return interval; the climate "
        "sensitivity $\\beta_T$ is inverted from the projected "
        "intensification; the severity moments come from burn-severity class "
        "fractions; and the interannual spread is inverted from the largest "
        "anomaly in the regional record.",
        "tab:calibration",
        "%.4g",
    )
    return df


def table_measures():
    """The available measures, their costs, exposure and fire-adjusted credit."""
    rows = []
    for name, region in REGIONS.items():
        data = solved(name)
        m = data["moments"]
        for i, store in enumerate(data["portfolio"].stores):
            rows.append(
                {
                    "region": region.label,
                    "measure": store.label,
                    "mean_storage_yr": store.intervention.mean_storage_time,
                    "exposure": EXPOSURE.get(store.name, np.nan),
                    "unit_cost_usd_per_t": UNIT_COSTS.get(store.name, np.nan),
                    "capacity_gt": (store.max_scale or np.nan) / 1e12,
                    "cooling_deterministic": m.deterministic[i],
                    "cooling_mean": m.mean[i],
                    "cooling_sd": m.std[i],
                    "loss_fraction": m.loss_fraction[i],
                    "survival_100yr": store.survival_probability(region.horizon),
                }
            )
    df = pd.DataFrame(rows)
    save_table(df, "measures")

    sub = df[df.region == REGIONS["western_us"].label]
    pretty = pd.DataFrame(
        {
            "Measure": sub["measure"],
            "$\\bar\\tau$ (yr)": sub["mean_storage_yr"].replace(np.inf, np.nan),
            "Exposed": sub["exposure"],
            "Cost (\\$/t)": sub["unit_cost_usd_per_t"],
            "Cap (Gt)": sub["capacity_gt"],
            "$b_i$": sub["cooling_deterministic"] * 1e14,
            "$\\mu_i$": sub["cooling_mean"] * 1e14,
            "$\\sigma_i$": sub["cooling_sd"] * 1e14,
            "Loss": sub["loss_fraction"],
        }
    )
    write_tex(
        pretty,
        "measures",
        "\\textbf{Measures available in the western United States case.} "
        "Cooling is per unit deployment in units of "
        "$10^{-14}$\\,K\\,yr\\,kg$^{-1}$: $b_i$ under deterministic "
        "durability, $\\mu_i$ and $\\sigma_i$ the mean and standard deviation "
        "under fire risk. ``Loss'' is the share of the deterministic credit "
        "that fire removes in expectation, and is the systematic over-credit "
        "of deterministic accounting.",
        "tab:measures",
        "%.3g",
    )
    return df


def table_premium():
    """The fire premium at each confidence, for both regions."""
    frames = []
    for name, region in REGIONS.items():
        data = solved(name)
        prem = data["premium"].copy()
        prem.insert(0, "region", region.label)
        prem["mean_over_credit"] = data["premium"].attrs["mean_over_credit"]
        prem["deterministic_cost"] = data["premium"].attrs["deterministic_cost"]
        prem["expectation_cost"] = data["premium"].attrs["expectation_cost"]
        frames.append(prem)
    df = pd.concat(frames, ignore_index=True)
    save_table(df, "premium")

    rows = []
    for name, region in REGIONS.items():
        data = solved(name)
        prem = data["premium"].set_index("confidence")
        ceil = data["ceiling"]
        entry = {"Region": region.label}
        for eta in HEADLINE:
            if eta in prem.index and bool(prem.loc[eta, "feasible"]):
                entry["$\\eta={:.2f}$".format(eta)] = (
                    100.0 * float(prem.loc[eta, "premium_vs_deterministic"])
                )
            else:
                entry["$\\eta={:.2f}$".format(eta)] = np.nan
        entry["Mean only"] = 100.0 * data["premium"].attrs["mean_over_credit"]
        entry["$\\eta_{\\max}$ exposed"] = ceil["confidence_max_exposed_only"]
        rows.append(entry)
    write_tex(
        pd.DataFrame(rows),
        "premium",
        "\\textbf{The fire premium.} Additional cost of achieving forcing "
        "neutrality at confidence $\\eta$, as a percentage of the cost under "
        "deterministic durability. ``Mean only'' is the part attributable to "
        "the expected loss of cooling, which any inventory owes regardless of "
        "the confidence sought; the remainder is the price of the guarantee. "
        "$\\eta_{\\max}$ is the confidence ceiling of the sub-portfolio that "
        "fire can reach.",
        "tab:premium",
        "%.3g",
    )
    return df


def table_composition():
    """Deployment and cooling share of every measure at each confidence."""
    frames = []
    for name, region in REGIONS.items():
        data = solved(name)
        fp = data["portfolio"]
        m = data["moments"]
        protected = np.array([s.hazard.is_inert for s in fp.stores])
        det = data["deterministic"]
        det_cool = det.alpha * m.deterministic
        rows = [
            {
                "region": region.label,
                "case": "deterministic",
                "confidence": np.nan,
                "cost": float(det.cost),
                "total_deployment_gt": float(det.alpha.sum()) / 1e12,
                "protected_share": float(det_cool[protected].sum() / det_cool.sum()),
                **{
                    "share_" + n: float(c / det_cool.sum())
                    for n, c in zip(fp.names, det_cool)
                },
            }
        ]
        for eta in CONFIDENCES:
            res = data["results"][eta]
            if not res.feasible:
                continue
            cool = res.alpha * m.mean
            rows.append(
                {
                    "region": region.label,
                    "case": "robust",
                    "confidence": float(eta),
                    "cost": float(res.cost),
                    "total_deployment_gt": float(res.alpha.sum()) / 1e12,
                    "protected_share": float(cool[protected].sum() / cool.sum()),
                    **{
                        "share_" + n: float(c / cool.sum())
                        for n, c in zip(fp.names, cool)
                    },
                }
            )
        frames.append(pd.DataFrame(rows))
    df = pd.concat(frames, ignore_index=True)
    save_table(df, "composition")

    name = "western_us"
    data = solved(name)
    fp = data["portfolio"]
    m = data["moments"]
    cols = {"Measure": [s.label for s in fp.stores]}
    det = data["deterministic"]
    dc = det.alpha * m.deterministic
    cols["Deterministic"] = dc / dc.sum()
    for eta in HEADLINE:
        res = data["results"][eta]
        if not res.feasible:
            continue
        c = res.alpha * m.mean
        cols["$\\eta={:.2f}$".format(eta)] = c / c.sum()
    write_tex(
        pd.DataFrame(cols),
        "composition",
        "\\textbf{Composition of the robust portfolio, western United "
        "States.} Share of delivered cooling supplied by each measure. The "
        "deterministic column credits every measure as though no fire "
        "occurred; the remaining columns hold neutrality with the stated "
        "confidence. Cooling migrates out of the measures fire can reach as "
        "the guarantee tightens.",
        "tab:composition",
        "%.3f",
    )
    return df


def table_variance():
    """How the variance of delivered cooling decomposes."""
    rows = []
    for name, region in REGIONS.items():
        data = solved(name)
        m = data["moments"]
        fp = data["portfolio"]
        for i, store in enumerate(fp.stores):
            if store.hazard.is_inert:
                continue
            tot = float(m.covariance[i, i])
            rows.append(
                {
                    "region": region.label,
                    "measure": store.label,
                    "variance_total": tot,
                    "variance_idiosyncratic": float(m.idiosyncratic[i, i]),
                    "variance_common": float(m.common[i, i]),
                    "common_share": float(m.common[i, i] / tot) if tot > 0 else np.nan,
                    "coefficient_of_variation": float(m.coefficient_of_variation[i]),
                }
            )
    df = pd.DataFrame(rows)
    save_table(df, "variance_decomposition")
    return df


def table_sources():
    """The published aggregates the calibration rests on."""
    rows = []
    for key, entry in PUBLISHED.items():
        rows.append(
            {
                "quantity": key,
                "value": entry.get("value"),
                "units": entry.get("units", ""),
                "period": entry.get("period", ""),
                "source": entry.get("source", ""),
                "note": entry.get("note", ""),
            }
        )
    df = pd.DataFrame(rows)
    save_table(df, "sources")
    return df


def main():
    table_sources()
    cal = table_calibration()
    meas = table_measures()
    prem = table_premium()
    comp = table_composition()
    var = table_variance()

    vals = {}
    for name, region in REGIONS.items():
        data = solved(name)
        m = data["moments"]
        fp = data["portfolio"]
        exposed = np.array([not s.hazard.is_inert for s in fp.stores])
        vals["loss_fraction_max_" + name] = float(np.nanmax(m.loss_fraction[exposed]))
        vals["loss_fraction_min_" + name] = float(np.nanmin(m.loss_fraction[exposed]))
        vals["required_cooling_" + name] = data["required_cooling"]
        vals["deterministic_cost_" + name] = float(data["deterministic"].cost)
    write_values(vals)
    print()
    print("  tables written: sources, calibration, measures, premium, "
          "composition, variance_decomposition")


if __name__ == "__main__":
    main()
